<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:property name="rob_name" value="buggy" />

	<xacro:property name="base_mass" value="7.0"/>
	<xacro:property name="base_hight" value="0.125"/>
	<xacro:property name="base_width" value="0.3"/>
	<xacro:property name="base_length" value="0.4"/>
	<xacro:property name="base_Ix" value="${base_mass*(base_hight*base_hight+base_width*base_width)/12}"/>
	<xacro:property name="base_Iy" value="${base_mass*(base_length*base_length+base_hight*base_hight)/12}"/>
	<xacro:property name="base_Iz" value="${base_mass*(base_length*base_length+base_width*base_width)/12}"/>

	
	<xacro:property name="wheel_radius" value="0.1"/>
	<xacro:property name="wheel_length" value="0.05"/>
	<xacro:property name="wheel_mass" value="0.5"/>
	<xacro:property name="wheel_Iz" value="${wheel_mass*wheel_radius*wheel_radius/2}"/>
	<xacro:property name="wheel_Ix" value="${wheel_mass*(3*wheel_radius*wheel_radius+wheel_length*wheel_length)/12}"/>

	<!-- base of robot-->
	<xacro:macro name="base_link">
		<link name="base_link">
			<visual>
				<geometry>
					<box size="${base_length} ${base_width} ${base_hight}"/>
				</geometry>
				<material name="blue">
					<color rgba="0 0 .8 1"/>
				</material>
			</visual>
			<collision>
				<geometry>
					<box size="${base_length} ${base_width} ${base_hight}"/>
				</geometry>
			</collision>
			<inertial>
				<mass value="${base_mass}"/>
				<inertia ixx="${wheel_Ix}" ixy="0.0" ixz="0.0" iyy="${base_Iy}" iyz="0.0" izz="${base_Iz}"/>
			</inertial>
		</link>
		<gazebo reference="base_link">
			<turnGravityOff>false</turnGravityOff>
		</gazebo>

	</xacro:macro>
	<xacro:base_link/>


	<!--wheels-->

	<xacro:macro name="wheel" params="prefix xyz_offsets lr">	
		<link name="${prefix}_wheel">
			<visual>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0" /> 
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
				</geometry>
				<material name="black">
					<color rgba="0 0 0 1"/>
				</material>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0" /> 
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}"/>
				</geometry>
			</collision>
			<inertial>
				<mass value="${wheel_mass}"/>
				<inertia ixx="${wheel_Ix}" ixy="0.0" ixz="0.0" iyy="${wheel_Ix}" iyz="0.0" izz="${wheel_Iz}"/>
			</inertial>
		</link>

		<joint name="${prefix}_wheel_joint" type="continuous">
			<axis xyz="0 1 0"/>
			<parent link="base_link"/>
			<child link="${prefix}_wheel"/>
			<origin rpy="0 0 0" xyz="${xyz_offsets}"/>
			<limit effort="100" velocity="100"/>
			<joint_properties damping="0.0" friction="0.0"/>
		</joint>

		<gazebo reference="${prefix}_wheel">
 			<mu1 value="1" /> 
  			<mu2 value="1" />
  			<fdir1 value="0 0 1"/>
  			<turnGravityOff>false</turnGravityOff>
		</gazebo>
	</xacro:macro>

	<xacro:property name="wheel_x_sep" value="${base_length/4+0.05}"/>

	<xacro:wheel prefix="right_front" xyz_offsets="${wheel_x_sep} -${(base_width+wheel_length)/2} -${base_hight/4}" lr="1"/>

	<xacro:wheel prefix="right_rear" xyz_offsets="-${wheel_x_sep} -${(base_width+wheel_length)/2} -${base_hight/4}" lr="1"/>
	
	<xacro:wheel prefix="left_front" xyz_offsets="${wheel_x_sep} ${(base_width+wheel_length)/2} -${base_hight/4}" lr="0"/>
	
	<xacro:wheel prefix="left_rear" xyz_offsets="-${wheel_x_sep} ${(base_width+wheel_length)/2} -${base_hight/4}" lr="0"/>

	<gazebo reference="base_link">
		<material>Gazebo/Blue</material>
	</gazebo>
	<gazebo reference="right_front_wheel">
		<material>Gazebo/FlatBlack</material>
	</gazebo>
	<gazebo reference="right_rear_wheel">
		<material>Gazebo/FlatBlack</material>
	</gazebo>
	<gazebo reference="left_front_wheel">
		<material>Gazebo/FlatBlack</material>
	</gazebo>
	<gazebo reference="left_rear_wheel">
		<material>Gazebo/FlatBlack</material>
	</gazebo>

	<joint name="imu_joint" type="fixed">
    	<axis xyz="0 0 0"/> 
    	<origin xyz="0.0 0.0 0.0"/>
    	<parent link="base_link"/>
    	<child link="imu_link"/>
 	</joint>


 	<link name="imu_link">
 		<inertial>
 			<mass value="0.001"/>
 			<origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
 			<inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001"/>
 		</inertial>
 		<collision>
 			<origin rpy="0 0 0" xyz="0 0 0"/>
 			<geometry>
 				<box size=".001 .001 .001"/>
 			</geometry>
 		</collision>
 	</link>

 	<gazebo>
 		<plugin filename="libgazebo_ros_imu.so" name="imu_en_ros">
 			<alwaysOn>true</alwaysOn>
 			<updateRate>100.0</updateRate> 
 			<bodyName>imu_link</bodyName>
 			<topicName>imu_data</topicName>
 			<gaussianNoise>2.89e-08</gaussianNoise>
 			<xyzOffset>0.0 0.0 0.0</xyzOffset>
 			<rpyOffset>0.0 0.0 0.0</rpyOffset>
 		</plugin>
 		<turnGravityOff>false</turnGravityOff>
 	</gazebo>

	<gazebo>
		<plugin name="robot_controller" filename="libdiff_drive_gazebo_plugin.so">
			<cmd_vel_topic_name>cmd_vel</cmd_vel_topic_name>
			<odom_topic_name>odom</odom_topic_name>
			<joint_states_topic_name>joint_states</joint_states_topic_name>
			<left_wheel_0>left_front_wheel_joint</left_wheel_0>
			<left_wheel_1>left_rear_wheel_joint</left_wheel_1>
			<right_wheel_2>right_front_wheel_joint</right_wheel_2>
			<right_wheel_3>right_rear_wheel_joint</right_wheel_3>
			<wheel_separation>${base_width + wheel_length}</wheel_separation>
			<wheel_radius>0.1</wheel_radius>
			<torque>10.0</torque>
			<num_joints>4</num_joints>

		</plugin>
	</gazebo>


</robot>


