<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!--tilting unit-->


	<xacro:macro name="box_link" params="link_name hight width length mass">
		<link name="${link_name}">
			<visual>
				<geometry>
					<box size="${length} ${width} ${hight}"/>
				</geometry>
			</visual>
			<collision>
				<geometry>
					<box size="${length} ${width} ${hight}"/>
				</geometry>
			</collision>
			<inertial>
				<mass value="${mass}"/>
				<inertia ixx="${mass*(hight*hight+width*width)/12}" ixy="0.0" ixz="0.0" iyy="${mass*(length*length+hight*hight)/12}" iyz="0.0" izz="${mass*(length*length+width*width)/12}"/>
			</inertial>
		</link>
	</xacro:macro>

	<xacro:macro name="cylinder_link" params="link_name radius length mass">	
		<link name="${link_name}">
			<visual>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0" /> 
				<geometry>
					<cylinder length="${length}" radius="${radius}"/>
				</geometry>
			</visual>
			<inertial>
				<mass value="${mass}"/>
				<inertia ixx="${mass*(3*radius*radius+length*length)/12}" ixy="0.0" ixz="0.0" iyy="${mass*(3*radius*radius+length*length)/12}" iyz="0.0" izz="${mass*radius*radius/2}"/>
			</inertial>
		</link>
	</xacro:macro>


	<xacro:property name="tilt_base_mass" value="0.02"/>
	<xacro:property name="tilt_base_hight" value="0.01"/>
	<xacro:property name="tilt_base_width" value="0.1"/>
	<xacro:property name="tilt_base_length" value="0.1"/>

	<xacro:box_link link_name="tilt_base_link" hight="${tilt_base_hight}" width="${tilt_base_width}" length="${tilt_base_length}" mass="${tilt_base_mass}"/>

	<xacro:property name="plr_mass" value="1e-5"/>
	<xacro:property name="plr_radius" value="0.005"/>
	<xacro:property name="plr_length" value="0.001"/>

	<xacro:property name="pillar_mass" value="1e-5"/>
	<xacro:property name="pillar_hight" value="0.11"/>
	<xacro:property name="pillar_length" value="0.005"/>
	<xacro:property name="pillar_width" value="${plr_length}"/>

	<xacro:box_link link_name="pillar_1_link" hight="${pillar_hight}" width="${pillar_width}" length="${pillar_length}" mass="${pillar_mass}"/>

	<xacro:box_link link_name="pillar_2_link" hight="${pillar_hight}" width="${pillar_width}" length="${pillar_length}" mass="${pillar_mass}"/>

	<xacro:cylinder_link link_name="plr_1_link" radius="${plr_radius}" length="${plr_length}" mass="${plr_mass}"/>

	<xacro:cylinder_link link_name="plr_2_link" radius="${plr_radius}" length="${plr_length}" mass="${plr_mass}"/>

	<joint name="pillar_1_joint" type="fixed">
			<parent link="plr_1_link"/>
			<child link="pillar_1_link"/>
			<origin rpy="0 0 0" xyz="0 0 ${pillar_hight/2 + plr_radius}"/>
	</joint>

	<joint name="pillar_2_joint" type="fixed">
			<parent link="plr_2_link"/>
			<child link="pillar_2_link"/>
			<origin rpy="0 0 0" xyz="0 0 ${pillar_hight/2 + plr_radius}"/>
	</joint>

	<joint name="pillar_1_link_joint" type="fixed">
		<parent link="tilt_base_link"/>
		<child link="plr_1_link"/>
		<origin rpy="0 0 0" xyz="0 -${plr_length/2 + tilt_base_width/2} -${plr_radius/2}"/>
	</joint>

	<joint name="pillar_2_link_joint" type="fixed">
		<parent link="tilt_base_link"/>
		<child link="plr_2_link"/>
		<origin rpy="0 0 0" xyz="0 ${plr_length/2 + tilt_base_width/2} -${plr_radius/2}"/>
	</joint>

	<xacro:box_link link_name="rot_elem_link" hight="${tilt_base_hight}" width="${tilt_base_width}" length="${tilt_base_length}" mass="${tilt_base_mass}"/>

	<joint name="rot_elem_joint" type="continuous">
			<axis xyz="0 1 0"/>
			<parent link="pillar_1_link"/>
			<child link="rot_elem_link"/>
			<origin rpy="0 0 0" xyz="0  ${tilt_base_width/2 + plr_length/2} ${pillar_hight/2 - tilt_base_hight/2}"/>
			<limit effort="100" velocity="100"/>
			<joint_properties damping="0.0" friction="0.0"/>
	</joint>

	<gazebo reference="tilt_base_link">
		<material>Gazebo/FlatBlack</material>
	</gazebo>
	<gazebo reference="rot_elem_link">
		<material>Gazebo/FlatBlack</material>
	</gazebo>
	<gazebo reference="pillar_1_link">
		<material>Gazebo/FlatBlack</material>
	</gazebo>
	<gazebo reference="pillar_2_link">
		<material>Gazebo/FlatBlack</material>
	</gazebo>
	<gazebo reference="plr_1_link">
		<material>Gazebo/FlatBlack</material>
	</gazebo>
	<gazebo reference="plr_2_link">
		<material>Gazebo/FlatBlack</material>
	</gazebo>

	<!-- Hokuyo Laser -->
	<joint name="hokuyo_joint" type="fixed">
		<origin xyz="0 0 ${tilt_base_hight/2}" rpy="0 0 0"/>
		<parent link="rot_elem_link"/>
		<child link="hokuyo_link"/>
	</joint>


	<link name="hokuyo_link">
		<collision>
			<geometry>
				<box size="0.1 0.1 0.1"/>
			</geometry>
		</collision>
		<visual>
			<geometry>
				<mesh filename="package://tilting_unit_description/meshes/hokuyo.dae"/>
			</geometry>
		</visual>
		<inertial>
			<mass value="1e-5" />
			<inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
		</inertial>
	</link>

	<gazebo reference="hokuyo_link">
		<sensor name="head_hokuyo_sensor" type="ray">
			<visualize>false</visualize>
			<update_rate>40</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>720</samples>
						<resolution>1</resolution>
						<min_angle>-1.570796</min_angle>
						<max_angle>1.570796</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.10</min>
					<max>30.0</max>
					<resolution>0.01</resolution>
				</range>
				<noise>
					<type>gaussian</type>
					<mean>0.0</mean>
					<stddev>0.01</stddev>
				</noise>
			</ray>
			<plugin filename="libgazebo_ros_laser.so" name="gazebo_ros_head_hokuyo_controller">
				<topicName>/gazebo/laser_scan</topicName>
				<frameName>hokuyo_link</frameName>
			</plugin>
		</sensor>
		<turnGravityOff>false</turnGravityOff>
	</gazebo>



</robot>
